---
title: "Final Project"
author: "Samuel Chow"
date: "1/29/2020"
output: html_document
---

```{r}
library(readr)

players = read_csv("players.csv")
```


```{r}
acc = c("Boston College", "Clemson University", "Duke University", "Florida State University", "Georgia Institute of Technology", "University of Louisville", "University of Miami", "University of North Carolina", "North Carolina State University", "University of Pittsburgh", "Syracuse University", "University of Virginia", "Virginia Polytechnic Institute and State University", "Wake Forest University", "University of Notre Dame")

big10 = c("University of Illinois at Urbana-Champaign", "Indiana University", "University of Iowa", "University of Maryland", "University of Michigan", "University of Minnesota", "University of Nebraska", "Northwestern University", "Ohio State University", "Pennsylvania State University", "Purdue University", "Rutgers University", "University of Wisconsin", "Michigan State University")

big12 = c("Baylor University", "Iowa State University", "University of Kansas", "Kansas State University", "University of Oklahoma", "Oklahoma State University", "Texas Christian University", "University of Texas at Austin", "Texas Tech University", "West Virginia University")

pac12 = c("University of Arizona", "Arizona State University", "University of California", "University of California, Los Angeles", "University of Colorado", "University of Oregon", "Oregon State University", "University of Southern California", "Stanford University", "University of Utah", "Washington State University", "University of Washington")

sec = c("University of Alabama", "University of Arkansas", "Auburn University", "University of Florida", "University of Georgia", "University of Kentucky", "Louisiana State University", "Mississippi State University", "University of Mississippi", "University of Missouri", "University of South Carolina", "University of Tennessee", "Texas A&M University", "Vanderbilt University")

players$conference = NA
players[players$college %in% acc,]$conference = "ACC"
players[players$college %in% big10,]$conference = "Big 10"
players[players$college %in% big12,]$conference = "Big 12"
players[players$college %in% pac12,]$conference = "Pac-12"
players[players$college %in% sec,]$conference = "SEC"

players[(!is.na(players$college) & is.na(players$conference)),]$conference= "Mid-Major"

height_ft = as.numeric(substr(players$height, 0, 1))
height_in = as.numeric(substr(players$height, 3, 4))

players$height_inches = height_ft * 12 + height_in

players$ncaa_efgpct = round((players$ncaa_fgpg + 0.5 *players$ncaa_3ptpg) / players$ncaa_fgapg, digits = 3)

write.csv(players, "players_updated.csv")


```



